# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.doBilinear <- function(xy, x, y, v) {
    .Call('raster_doBilinear', PACKAGE = 'raster', xy, x, y, v)
}

.doCellFromRowCol <- function(nrow, ncol, rownr, colnr) {
    .Call('raster_doCellFromRowCol', PACKAGE = 'raster', nrow, ncol, rownr, colnr)
}

.doCellFromXY <- function(ncols, nrows, xmin, xmax, ymin, ymax, x, y) {
    .Call('raster_doCellFromXY', PACKAGE = 'raster', ncols, nrows, xmin, xmax, ymin, ymax, x, y)
}

.doXYFromCell <- function(ncols, nrows, xmin, xmax, ymin, ymax, cell) {
    .Call('raster_doXYFromCell', PACKAGE = 'raster', ncols, nrows, xmin, xmax, ymin, ymax, cell)
}

.doFourCellsFromXY <- function(ncols, nrows, xmin, xmax, ymin, ymax, xy, duplicates, isGlobalLonLat) {
    .Call('raster_doFourCellsFromXY', PACKAGE = 'raster', ncols, nrows, xmin, xmax, ymin, ymax, xy, duplicates, isGlobalLonLat)
}

